version: '3.5'
services:
  frontend:
    build:
      context: frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "12000:80"

  server:
    build:
      context: Server
      dockerfile: .docker/Dockerfile
    ports:
      - "5200:5100"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1234abcd<>%&"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"


networks:
  default:
    name: calendar_network
